import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";
import { AuthProvider } from "./lib/AuthContext";

// Configure the Inter font
const inter = Inter({
  variable: "--font-inter", // Correct variable for Inter
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
         <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
